module_name: Block Top Menu
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - menu
  - top menu
  - navigation
description_short: The block top menu is the default top menu module for your shop
description: description.md
images:
  - image-1.png
license: AFL